// export MinuteHand from "./MinuteHand";
// export HourHand from "./HourHand";
// export ClockTicks from "./ClockTicks";
// export Pin from "./Pin";
// export HourIndicators from "./HourIndicators";
export { default as MinuteHand } from "./MinuteHand";
export { default as HourHand } from "./HourHand";
export { default as ClockTicks } from "./ClockTicks";
export { default as Pin } from "./Pin";
export { default as HourIndicators } from "./HourIndicators";
